apiVersion: v1
kind: Service
metadata:
  name: load-balancer

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    app: myapp
    type: load-balancer
